# Generated by Django 4.1.5 on 2023-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_version_remove_post_content_remove_post_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
