# Generated by Django 4.1.5 on 2023-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_version_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
